language: php
php: '7.2'
services:
- mysql
- apache2
addons:
  ssh_known_hosts:
  - welcome2the.cloud:22
before_install:
- openssl aes-256-cbc -K $encrypted_8aad41c1f77d_key -iv $encrypted_8aad41c1f77d_iv 
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- chmod 755 .travis/deploy.sh
before_script:
- composer update
script:
- vendor/bin/phpunit --bootstrap src/addcart.php tests/AddCartTest.php
- vendor/bin/phpunit --bootstrap src/checkout.php tests/CheckoutTest.php
- vendor/bin/phpunit --bootstrap src/listorder.php tests/ListOrderTest.php
- vendor/bin/phpunit --bootstrap src/listprod.php tests/ListProdTest.php
- vendor/bin/phpunit --bootstrap src/loaddata.php tests/LoadDataTest.php
- vendor/bin/phpunit --bootstrap src/order.php tests/OrderTest.php
- vendor/bin/phpunit --bootstrap src/showcart.php tests/ShowCartTest.php
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
