language: php
php: '7.2'
services:
- mysql
addons:
  ssh_known_hosts:
  - welcome2the.cloud:22
before_install:
- sudo apt-get install php-mysql 
- openssl aes-256-cbc -K $encrypted_8aad41c1f77d_key -iv $encrypted_8aad41c1f77d_iv 
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- chmod 755 .travis/deploy.sh
- mysql -e 'CREATE DATABASE testDatabase;'
- mysql -e "CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';"
- mysql -e "GRANT ALL ON testDatabase.* TO 'username'@'localhost'; flush privileges;"
- mysql -u root --default-character-set=utf8 testDatabase < src/data/createDatabase.sql
- echo "<?php function getDBLogin(){ \$username = \"username\"; \$password = \"password\"; \$database = \"testDatabase\"; \$server = \"localhost\"; return array(\$username, \$password, \$database, \$server);} ?>" > src/include/db_credentials.php 
before_script:
- composer update
script:
- vendor/bin/phpunit --bootstrap src/objects/Account.php tests/AccountTest.php
- vendor/bin/phpunit --bootstrap src/objects/Admin.php tests/AdminTest.php
- vendor/bin/phpunit --bootstrap src/objects/Category.php tests/CategoryTest.php
- vendor/bin/phpunit --bootstrap src/objects/Login.php tests/LoginTest.php
- vendor/bin/phpunit --bootstrap src/objects/Order.php tests/OrderTest.php
- vendor/bin/phpunit --bootstrap src/objects/Product.php tests/ProductTest.php
- vendor/bin/phpunit --bootstrap src/objects/ShoppingCart.php tests/ShoppingCartTest.php
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
